module.exports = {
  players: [
  {
    "id": 0,
    "firstName": "Giannis",
    "lastName": "Antetokounmpo",
    "yearsInLeague": "4 years",
    "team": "Milwaukee Bucks",
    "ppg": "27.2",
    "rpg": "10.0",
    "apg": "4.8",
    "image": "http://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3032977.png&w=350&h=254",
    "url": "http://www.nba.com/players/giannis/antetokounmpo/203507"
  },

  {
    "id": 66,
    "firstName": "Kyrie",
    "lastName": "Irving",
    "yearsInLeague": "6 years",
    "team": "Boston Celtics",
    "ppg": "24.4",
    "rpg": "3.8",
    "apg": "5.1",
    "image": "http://images.performgroup.com/di/library/omnisport/1f/37/irving-kyrie-usnews-getty-ftr_1apvmmmdgk9pu1f07zmbm5ugg6.jpg?t=-1945979623&w=960&quality=70",
    "url": "http://www.nba.com/players/kyrie/irving/202681"
  },
  {
    "id": 69,
    "firstName": "Lebron",
    "lastName": "James",
    "yearsInLeague": "15 years",
    "team": "Cleveland Cavaliers",
    "ppg": "27.6",
    "rpg": "8.6",
    "apg": "9.1",
    "image": "https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/2544.png",
    "url": "http://www.nba.com/players/lebron/james/2544"
  },
  {
    "id": 69,
    "firstName": "Nikola",
    "lastName": "Jokic",
    "yearsInLeague": "2 years",
    "team": "Denver Nuggets",
    "ppg": "17.8",
    "rpg": "10.5",
    "apg": "6.0",
    "image": "http://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3112335.png&w=350&h=254",
    "url": "http://www.nba.com/players/nikola/jokic/203999"
  },
  {
    "id": 70,
    "firstName": "Kawhi",
    "lastName": "Leonard",
    "yearsInLeague": "6 years",
    "team": "San Antonio Spurs",
    "ppg": "16.2",
    "rpg": "4.7",
    "apg": "2.3",
    "image": "http://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/6450.png&w=350&h=254",
    "url": "http://www.nba.com/players/kawhi/leonard/202695"
  },
  {
    "id": 1,
    "firstName": "LaMarcus",
    "lastName": "Aldridge",
    "yearsInLeague": "11 years",
    "team": "San Antonio Spurs",
    "ppg": "23.1",
    "rpg": "8.3",
    "apg": "2.1",
    "image": "http://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/2983.png&w=350&h=254",
    "url": "http://www.nba.com/players/lamarcus/aldridge/200746"
  },

  {
    "id": 2,
    "firstName": "Bradley",
    "lastName": "Beal",
    "yearsInLeague": "5 years",
    "team": "Washington Wizards",
    "ppg": "22.9",
    "rpg": "4.4",
    "apg": "4.6",
    "image": "http://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/6580.png&w=350&h=254",
    "url": "http://www.nba.com/players/bradley/beal/203078"
  },


  {
    "id": 18,
    "firstName": "Goran",
    "lastName": "Dragic",
    "yearsInLeague": "9 years",
    "team": "Miami Heat",
    "ppg": "17.4",
    "rpg": "4.0",
    "apg": "4.9",
    "image": "http://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3423.png&w=350&h=254",
    "url": "http://www.nba.com/players/goran/dragic/201609"
  },
  {
    "id": 20,
    "firstName": "Andre",
    "lastName": "Drummond",
    "yearsInLeague": "5 years",
    "team": "Detroit Pistons",
    "ppg": "14.8",
    "rpg": "15.9",
    "apg": "3.1",
    "image": "http://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/6585.png&w=350&h=254",
    "url": "http://www.nba.com/players/andre/drummond/203083"
  },
  {
    "id": 22,
    "firstName": "Kevin",
    "lastName": "Durant",
    "yearsInLeague": "10 years",
    "team": "Golden State Warriors",
    "ppg": "26.6",
    "rpg": "6.8",
    "apg": "5.4",
    "image": "http://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3202.png&w=350&h=254",
    "url": "http://www.nba.com/players/kevin/durant/201142"
  },
  {
    "id": 28,
    "firstName": "Joel",
    "lastName": "Embiid",
    "yearsInLeague": "3 years",
    "team": "Philadelphia 76ers",
    "ppg": "22.9",
    "rpg": "11.0",
    "apg": "3.2",
    "image": "http://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3059318.png&w=350&h=254",
    "url": "http://www.nba.com/players/joel/embiid/203954"
  },
  {
    "id": 29,
    "firstName": "Tyreke",
    "lastName": "Evans",
    "yearsInLeague": "8 years",
    "team": "Memphis Grizzlies",
    "ppg": "19.4",
    "rpg": "5.1",
    "apg": "5.2",
    "image": "http://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3983.png&w=350&h=254",
    "url": "http://www.nba.com/players/tyreke/evans/201936"
  },
  {
    "id": 30,
    "firstName": "Marc",
    "lastName": "Gasol",
    "yearsInLeague": "9 years",
    "team": "Memphis Grizzlies",
    "ppg": "17.4",
    "rpg": "8.4",
    "apg": "4.2",
    "image": "http://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3206.png&w=350&h=254",
    "url": "http://www.nba.com/players/marc/gasol/201188"
  },
  {
    "id": 31,
    "firstName": "Pau",
    "lastName": "Gasol",
    "yearsInLeague": "16 years",
    "team": "San Antonio Spurs",
    "ppg": "10.5",
    "rpg": "8.1",
    "apg": "3.1",
    "image": "http://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/996.png&w=350&h=254",
    "url": "http://www.nba.com/players/pau/gasol/2200"
  },
  {
    "id": 33,
    "firstName": "Paul",
    "lastName": "George",
    "yearsInLeague": "7 years",
    "team": "Oklahoma City Thunder",
    "ppg": "21.6",
    "rpg": "5.6",
    "apg": "3.4",
    "image": "http://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4251.png&w=350&h=254",
    "url": "http://www.nba.com/players/paul/george/202331"
  },
  {
    "id":34,
    "firstName": "Manu",
    "lastName": "Ginobili",
    "yearsInLeague": "15 years",
    "team": "San Antonio Spurs",
    "ppg": "8.7",
    "rpg": "2.1",
    "apg": "2.5",
    "image": "http://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/272.png&w=350&h=254",
    "url": "http://www.nba.com/players/manu/ginobili/1938"
  },
  {
    "id": 40,
    "firstName": "Rudy",
    "lastName": "Gobert",
    "yearsInLeague": "4 years",
    "team": "Utah Jazz",
    "ppg": "14.0",
    "rpg": "10.0",
    "apg": "1.4",
    "image": "http://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3032976.png&w=350&h=254",
    "url": "http://www.nba.com/players/rudy/gobert/203497"
  },
  {
    "id": 41,
    "firstName": "Eric",
    "lastName": "Gordon",
    "yearsInLeague": "9 years",
    "team": "Houston Rockets",
    "ppg": "18.3",
    "rpg": "2.5",
    "apg": "2.2",
    "image": "http://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3431.png&w=350&h=254",
    "url": "http://www.nba.com/players/eric/gordon/201569"
  },

  {
    "id": 44,
    "firstName": "Draymond",
    "lastName": "Green",
    "yearsInLeague": "5 years",
    "team": "Golden State Warriors",
    "ppg": "11.3",
    "rpg": "7.9",
    "apg": "7.3",
    "image": "http://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/6589.png&w=350&h=254",
    "url": "http://www.nba.com/players/draymond/green/203110"
  },
  {
    "id": 46,
    "firstName": "Blake",
    "lastName": "Griffin",
    "yearsInLeague": "8 years",
    "team": "Detroit Pistons",
    "ppg": "27.2",
    "rpg": "10.0",
    "apg": "4.8",
    "image": "http://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3989.png&w=350&h=254",
    "url": "http://www.nba.com/players/blake/griffin/201933"
  },
  {
    "id": 50,
    "firstName": "Tim",
    "lastName": "Hardaway",
    "yearsInLeague": "4 years",
    "team": "New York Knicks",
    "ppg": "27.2",
    "rpg": "10.0",
    "apg": "4.8",
    "image": "http://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/2528210.png&w=350&h=254",
    "url": "http://www.nba.com/players/tim/hardaway_jr./203501"
  },
  {
    "id": 52,
    "firstName": "James",
    "lastName": "Harden",
    "yearsInLeague": "8 years",
    "team": "Houston Rockets",
    "ppg": "27.2",
    "rpg": "10.0",
    "apg": "4.8",
    "image": "http://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3992.png&w=350&h=254",
    "url": "http://www.nba.com/players/james/harden/201935"
  },
  {
    "id": 54,
    "firstName": "Tobias",
    "lastName": "Harris",
    "yearsInLeague": "6 years",
    "team": "LA Clippers",
    "ppg": "21.4",
    "rpg": "7.4",
    "apg": "5.8",
    "image": "http://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/6440.png&w=350&h=254",
    "url": "http://www.nba.com/players/tobias/harris/202699"
  },
  {
    "id": 56,
    "firstName": "Gordon",
    "lastName": "Hayward",
    "yearsInLeague": "7 years",
    "team": "Boston Celtics",
    "ppg": "2.0",
    "rpg": "1.0",
    "apg": "0.0",
    "image": "http://image.masslive.com/home/mass-media/width600/img/celtics_impact/photo/gordon-hayward-0ef6795df876d180.jpg",
    "url": "http://www.nba.com/players/gordon/hayward/202330"
  },
  {
    "id": 58,
    "firstName": "Al",
    "lastName": "Horford",
    "yearsInLeague": "10 years",
    "team": "Boston Celtics",
    "ppg": "12.8",
    "rpg": "7.4",
    "apg": "4.9",
    "image": "http://www.espn.com/nba/player/_/id/3213/al-horford",
    "url": "http://www.nba.com/players/al/horford/201143"
  },
  {
    "id": 60,
    "firstName": "Dwight",
    "lastName": "Howard",
    "yearsInLeague": "13 years",
    "team": "Charlotte Hornets",
    "ppg": "16.7",
    "rpg": "12.3",
    "apg": "1.3",
    "image": "http://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/2384.png&w=350&h=254",
    "url": "http://www.nba.com/players/dwight/howard/2730"
  },
  {
    "id": 62,
    "firstName": "Serge",
    "lastName": "Ibaka",
    "yearsInLeague": "8 years",
    "team": "Toronto Raptors",
    "ppg": "12.5",
    "rpg": "6.2",
    "apg": "0.5",
    "image": "http://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3439.png&w=350&h=254",
    "url": "http://www.nba.com/players/serge/ibaka/201586"
  },
  {
    "id": 64,
    "firstName": "Andre",
    "lastName": "Iguodala",
    "yearsInLeague": "13 years",
    "team": "Golden State Warriors",
    "ppg": "6.1",
    "rpg": "3.8",
    "apg": "3.2",
    "image": "http://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/2386.png&w=350&h=254",
    "url": "http://www.nba.com/players/andre/iguodala/2738"
  },
  {
    "id": 3,
    "firstName": "Eric",
    "lastName": "Bledsoe",
    "yearsInLeague": "7 years",
    "team": "Milwaukee Bucks",
    "ppg": "17.3",
    "rpg": "3.8",
    "apg": "4.8",
    "image": "http://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4238.png&w=350&h=254",
    "url": "http://www.nba.com/players/eric/bledsoe/202339"
  },
  {
    "id": 4,
    "firstName": "Devin",
    "lastName": "Booker",
    "yearsInLeague": "2 years",
    "team": "Phoenix Suns",
    "ppg": "24.9",
    "rpg": "4.5",
    "apg": "4.7",
    "image": "http://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3136193.png&w=350&h=254",
    "url": "http://www.nba.com/players/devin/booker/1626164"
  },
  {
    "id": 5,
    "firstName": "Jaylen",
    "lastName": "Brown",
    "yearsInLeague": "1 years",
    "team": "Boston Celtics",
    "ppg": "14.2",
    "rpg": "5.2",
    "apg": "1.7",
    "image": "http://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3917376.png&w=350&h=254",
    "url": "http://www.nba.com/players/jaylen/brown/1627759"
  },
  {
    "id": 6,
    "firstName": "Jimmy",
    "lastName": "Butler",
    "yearsInLeague": "6 years",
    "team": "Minnesota Timberwolves",
    "ppg": "22.2",
    "rpg": "5.4",
    "apg": "5.0",
    "image": "http://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/6430.png&w=350&h=2544",
    "url": "http://www.nba.com/players/jimmy/butler/202710"
  },
  {
    "id": 7,
    "firstName": "Clint",
    "lastName": "Capela",
    "yearsInLeague": "3 years",
    "team": "Houston Rockets",
    "ppg": "14.1",
    "rpg": "11.0",
    "apg": "0.9",
    "image": "http://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3102529.png&w=350&h=254",
    "url": "http://www.nba.com/players/clint/capela/203991"
  },
  {
    "id": 8,
    "firstName": "DeMarcus",
    "lastName": "Cousins",
    "yearsInLeague": "7 years",
    "team": "New Orleans Pelicans",
    "ppg": "25.2",
    "rpg": "12.9",
    "apg": "5.4",
    "image": "http://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4258.png&w=350&h=254",
    "url": "http://www.nba.com/players/demarcus/cousins/202326"
  },
  {
    "id": 9,
    "firstName": "Robert",
    "lastName": "Covington",
    "yearsInLeague": "4 years",
    "team": "Philadelphia 76ers",
    "ppg": "12.8",
    "rpg": "5.4",
    "apg": "1.9",
    "image": "http://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/2490620.png&w=350&h=254",
    "url": "http://www.nba.com/players/robert/covington/203496"
  },
  {
    "id": 10,
    "firstName": "Stephen",
    "lastName": "Curry",
    "yearsInLeague": "8 years",
    "team": "Golden State Warriors",
    "ppg": "26.4",
    "rpg": "5.1",
    "apg": "6.1",
    "image": "http://2kmtcentral.com/img/players/18/generated/1612i1.png/cache-1508874901/1612i1.png",
    "url": "http://www.nba.com/players/stephen/curry/201939"
  },
  {
    "id": 11,
    "firstName": "Anthony",
    "lastName": "Davis",
    "yearsInLeague": "5 years",
    "team": "New Orleans Pelicans",
    "ppg": "28.3",
    "rpg": "11.1",
    "apg": "2.3",
    "image": "http://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/6583.png&w=350&h=254",
    "url": "http://www.nba.com/players/anthony/davis/203076"
  },
  {
    "id": 15,
    "firstName": "DeMar",
    "lastName": "DeRozan",
    "yearsInLeague": "8 years",
    "team": "Toronto Raptors",
    "ppg": "23.3",
    "rpg": "3.9",
    "apg": "5.2",
    "image": "http://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3978.png&w=350&h=254",
    "url": "http://www.nba.com/players/demar/derozan/201942"
  },
  {
    "id": 72,
    "firstName": "Damian",
    "lastName": "Lillard",
    "yearsInLeague": "5 years",
    "team": "Portland Trail Blazers",
    "ppg": "26.8",
    "rpg": "4.5",
    "apg": "6.5",
    "image": "http://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/6606.png&w=350&h=254",
    "url": "http://www.nba.com/players/damian/lillard/203081"
  },

  {
    "id": 74,
    "firstName": "Kevin",
    "lastName": "Love",
    "yearsInLeague": "9 years",
    "team": "Cleveland Cavaliers",
    "ppg": "17.7",
    "rpg": "9.2",
    "apg": "1.7",
    "image": "http://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3449.png&w=350&h=254",
    "url": "http://www.nba.com/players/kevin/love/201567"
  },
  {
    "id": 76,
    "firstName": "Kyle",
    "lastName": "Lowry",
    "yearsInLeague": "11 years",
    "team": "Toronto Raptors",
    "ppg": "16.6",
    "rpg": "5.6",
    "apg": "6.8",
    "image": "http://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3012.png&w=350&h=254",
    "url": "http://www.nba.com/players/kyle/lowry/200768"
  },

  {
    "id": 78,
    "firstName": "Khris",
    "lastName": "Middleton",
    "yearsInLeague": "5 years",
    "team": "Milwaukee Bucks",
    "ppg": "20.1",
    "rpg": "5.2",
    "apg": "4.0",
    "image": "http://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/6609.png&w=350&h=254",
    "url": "http://www.nba.com/players/khris/middleton/203114"
  },
  {
    "id": 80,
    "firstName": "Paul",
    "lastName": "Millsap",
    "yearsInLeague": "11 years",
    "team": "Denver Nuggets",
    "ppg": "14.1",
    "rpg": "6.2",
    "apg": "2.7",
    "image": "http://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3015.png&w=350&h=254",
    "url": "http://www.nba.com/players/paul/millsap/200794"
  },
  {
    "id": 83,
    "firstName": "Donovan",
    "lastName": "Mitchell",
    "yearsInLeague": "Rookie",
    "team": "Utah Jazz",
    "ppg": "20.3",
    "rpg": "3.6",
    "apg": "3.6",
    "image": "http://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3908809.png&w=350&h=254",
    "url": "http://www.nba.com/players/donovan/mitchell/1628378"
  },
  {
    "id": 86,
    "firstName": "Larry",
    "lastName": "Nance",
    "yearsInLeague": "2 years",
    "team": "Cleveland Cavaliers",
    "ppg": "9.1",
    "rpg": "7.1",
    "apg": "3.1",
    "image": "http://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/2580365.png&w=350&h=254",
    "url": "http://www.nba.com/players/larry/nance_jr./1626204"
  },
  {
    "id": 88,
    "firstName": "Dirk",
    "lastName": "Nowitzki",
    "yearsInLeague": "19 years",
    "team": "Dallas Mavericks", 
    "ppg": "12.1",
    "rpg": "5.7",
    "apg": "1.6",
    "image": "http://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/609.png&w=350&h=254",
    "url": "http://www.nba.com/players/dirk/nowitzki/1717"
  },
  {
    "id": 90,
    "firstName": "Victor",
    "lastName": "Oladipo",
    "yearsInLeague": "4 years",
    "team": "Indiana Pacers", 
    "firstName": "Jabari",
    "ppg": "23.2",
    "rpg": "5.3",
    "apg": "4.2",
    "Image": "http://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/2527963.png&w=350&h=254",
    "url": "http://www.nba.com/players/victor/oladipo/203506"
  },
  {
    "id": 92,
    "firstName": "Jabari",
    "lastName": "Parker",
    "yearsInLeague": "3 years",
    "team": "Milwaukee Bucks",
    "ppg": "11.0",
    "rpg": "4.0",
    "apg": "1.5",
    "image": "http://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3056600.png&w=350&h=254",
    "url": "http://www.nba.com/players/jabari/parker/203953"
  },
  {
    "id": 94,
    "firstName": "Tony",
    "lastName": "Parker",
    "yearsInLeague": "16 years",
    "team": "San Antonio Spurs",
    "ppg": "8.1",
    "rpg": "1.9",
    "apg": "3.8",
    "Image": "http://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/1015.png&w=350&h=254",
    "url": "http://www.nba.com/players/tony/parker/2225"
  },
  {
    "id": 96,
    "firstName": "Chris",
    "lastName": "Paul",
    "yearsInLeague": "12 years",
    "team": "Houston Rockets",
    "ppg": "18.6",
    "rpg": "5.6",
    "apg": "8.0",
    "image": "http://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/2779.png&w=350&h=254",
    "url": "http://www.nba.com/players/chris/paul/101108"
  },
  {
    "id": 98,
    "firstName": "Kristaps",
    "lastName": "Porzingis",
    "yearsInLeague": "2 years",
    "team": "New York Knicks",
    "ppg": "22.7",
    "rpg": "6.6",
    "apg": "1.2",
    "image": "http://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3102531.png&w=350&h=254",
    "url": "http://www.nba.com/players/kristaps/porzingis/204001"
  },
  {
    "id": 100,
    "firstName": "JJ",
    "lastName": "Redick",
    "yearsInLeague": "11 years",
    "team": "Philadelphia 76ers",
    "ppg": "16.5",
    "rpg": "2.6",
    "apg": "3.0",
    "image": "http://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3024.png&w=350&h=254",
    "url": "http://www.nba.com/players/jj/redick/200755"
  },
  {
    "id": 102,
    "firstName": "Rajon",
    "lastName": "Rondo",
    "yearsInLeague": "11 years",
    "team": "New Orleans Pelicans",
    "ppg": "8.2",
    "rpg": "4.0",
    "apg": "7.9",
    "image": "http://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3026.png&w=350&h=254",
    "url": "http://www.nba.com/players/rajon/rondo/200765"
  },
  {
    "id": 104,
    "firstName": "Ricky",
    "lastName": "Rubio",
    "yearsInLeague": "6 years",
    "team": "Utah Jazz",
    "ppg": "12.8",
    "rpg": "4.5",
    "apg": "5.4",
    "Image": "http://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4011.png&w=350&h=254",
    "url": "http://www.nba.com/players/ricky/rubio/201937"
  },
  {
    "id": 106,
    "firstName": "D'Angelo",
    "lastName": "Russell",
    "yearsInLeague": "2 years",
    "team": "Brooklyn Nets",
    "ppg": "16.0",
    "rpg": "4.0",
    "apg": "5.1",
    "image": "http://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3136776.png&w=350&h=254",
    "url": "http://www.nba.com/players/d'angelo/russell/1626156"
  },

  {
    "id": 108,
    "firstName": "Dario",
    "lastName": "Saric",
    "yearsInLeague": "1 years",
    "team": "Philadelphia 76ers",
    "ppg": "15.1",
    "rpg": "6.9",
    "apg": "2.6",
    "image": "http://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3032978.png&w=350&h=254",
    "url": "http://www.nba.com/players/dario/saric/203967"
  },
  {
    "id": 110,
    "firstName": "Dennis",
    "lastName": "Smith",
    "yearsInLeague": "Rookie",
    "team": "Dallas Mavericks", 
    "ppg": "15.2",
    "rpg": "3.7",
    "apg": "5.0",
    "image": "http://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4065697.png&w=350&h=254",
    "url": "http://www.nba.com/players/dennis/smith_jr./1628372"
  },

  {
    "id": 112,
    "firstName": "Jayson",
    "lastName": "Tatum",
    "yearsInLeague": "Rookie",
    "team": "Boston Celtics",  
    "ppg": "13.7",
    "rpg": "5.1",
    "apg": "1.5",
    "image": "http://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4065648.png&w=350&h=254",
    "url": "http://www.nba.com/players/jayson/tatum/1628369"
  },
  {
    "id": 113,
    "firstName": "Isaiah",
    "lastName": "Thomas",
    "yearsInLeague": "6 years",
    "team": "Los Angeles Lakers", 
    "ppg": "15.2",
    "rpg": "2.1",
    "apg": "4.8",
    "image": "http://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/6472.png&w=350&h=254",
    "url": "http://www.nba.com/players/isaiah/thomas/202738"
  },
  {
    "id": 114,
    "firstName": "Klay",
    "lastName": "Thompson",
    "yearsInLeague": "6 years",
    "team": "Golden State Warriors", 
    "ppg": "19.7",
    "rpg": "3.8",
    "apg": "2.7",
    "image": "http://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/6475.png&w=350&h=254",
    "url": "http://www.nba.com/players/klay/thompson/202691"
  },
  
  {
    "id": 116,
    "firstName": "Karl-Anthony",
    "lastName": "Towns",
    "yearsInLeague": "2 years",
    "team": "Minnesota Timberwolves", 
    "ppg": "21.2",
    "rpg": "12.2",
    "apg": "2.4",
    "image": "http://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3136195.png&w=350&h=254",
    "url": "http://www.nba.com/players/karl-anthony/towns/1626157"
  },
  {
    "id": 120,
    "firstName": "Dwyane",
    "lastName": "Wade",
    "yearsInLeague": "14 years",
    "team": "Miami Heat", 
    "ppg": "11.6",
    "rpg": "3.8",
    "apg": "3.4",
    "image": "http://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/1987.png&w=350&h=254",
    "url": "http://www.nba.com/players/dwyane/wade/2548"
  },
  {
    "id": 122,
    "firstName": "Kemba",
    "lastName": "Walker",
    "yearsInLeague": "6 years",
    "team": "Charlotte Hornets", 
    "ppg": "23.0",
    "rpg": "3.2",
    "apg": "5.7",
    "image": "http://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/6479.png&w=350&h=254",
    "url": "http://www.nba.com/players/kemba/walker/202689"
  },
  {
    "id": 124,
    "firstName": "John",
    "lastName": "Wall",
    "yearsInLeague": "7 years",
    "team": "Washington Wizards", 
    "ppg": "19.4",
    "rpg": "3.6",
    "apg": "9.3", 
    "image": "http://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4237.png&w=350&h=254",
    "url": "http://www.nba.com/players/john/wall/202322"
  },
  {
    "id": 126,
    "firstName": "Russell",
    "lastName": "Westbrook",
    "yearsInLeague": "9 years",
    "team": "Oklahoma City Thunder", 
    "ppg": "25.4",
    "rpg": "9.7",
    "apg": "10.2",
    "image": "http://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3468.png&w=350&h=254",
    "url": "http://www.nba.com/players/russell/westbrook/201566"
  },
  {
    "id": 128,
    "firstName": "Hassan",
    "lastName": "Whiteside",
    "yearsInLeague": "7 years",
    "team": "Miami Heat", 
    "ppg": "14.3",
    "rpg": "11.8",
    "apg": "1.8",
    "image": "http://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4262.png&w=350&h=254",
    "url": "http://www.nba.com/players/hassan/whiteside/202355"
  },
  {
    "id": 130,
    "firstName": "Andrew",
    "lastName": "Wiggins",
    "yearsInLeague": "3 years",
    "team": "Minnesota Timberwolves", 
    "ppg": "18.1",
    "rpg": "4.3",
    "apg": "1.9",
    "image": "http://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3059319.png&w=350&h=254",
    "url": "http://www.nba.com/players/andrew/wiggins/203952"
  },
  {
    "id": 134,
    "firstName": "Lou",
    "lastName": "Williams",
    "yearsInLeague": "12 years",
    "team": "LA Clippers", 
    "ppg": "22.7",
    "rpg": "2.6",
    "apg": "5.4",
    "image": "http://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/2799.png&w=350&h=254",
    "url": "http://www.nba.com/players/lou/williams/101150"
  },
  {
    "id": 140,
    "firstName": "Ben",
    "lastName": "Simmons",
    "yearsInLeague": "Rookie",
    "team": "Philadelphia 76ers", 
    "ppg": "15.8",
    "rpg": "8.0",
    "apg": "8.0",
    "image": "https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/1627732.png",
    "url": "http://www.nba.com/players/ben/simmons/1627732"
  }
],
}